### PR TITLE
Update data fetcher constructor

### PR DESCRIPTION
**Pull request by rmarianski**
@zerebubuth, @iandees could you review please?

@iandees I'm assuming that it's ok for the minimum and maximum values to be the same for tileserver.

### CODE REVIEW

**Comment by iandees** [comment]
Hmm, it might not be a good idea to set the max connections to be the same as min. Let me look a little closer 🔍 .

**Comment by iandees** [comment]
I might be off-by-one here, but I think if we set min and max to the same thing, we won't be able to request all N connections because of this pair of lines: https://github.com/psycopg/psycopg2/blob/master/lib/pool.py#L90-L91

**Comment by rmarianski** [comment]
It still looks like we'd be ok to me because that branch will only get triggered if there's nothing in `self._pool`, which will have the minimum number of connections in it.

I deployed this branch to dev so we can wait to see if we get any errors in tileserver related to this after some usage.

**Comment by iandees** [comment]
Yep, you're right. I think we're OK here.

**Review by iandees — APPROVED** [review]

**Pull request merged**
