### PR TITLE
Enable Shapely speedups if they're available

### PR DESCRIPTION
**Pull request by iandees**
Like https://github.com/tilezen/mapbox-vector-tile/pull/91, but for tileserver.

### CODE REVIEW

**Comment by iandees** [comment]
(This probably isn't required, because Shapely enables speedups by default nowadays: https://github.com/Toblerity/Shapely/pull/252)

**Comment by nvkelso** [comment]
@iandees My reading is we're using 1.4.3 and speedups weren't enabled by default until 1.6a1

- https://github.com/tilezen/tileserver/blob/master/requirements.txt#L18
- https://github.com/Toblerity/Shapely/blob/master/CHANGES.txt#L65-L91

**Comment by nvkelso** [comment]
LGTM, but let's get an review from @rmarianski before merging.

**Review by rmarianski — APPROVED** [review]

**Comment by rmarianski** [comment]
> My reading is we're using 1.4.3

Unrelated to this pr, but we're pegged to older versions of several packages now, with the only reason being consistent deployments. We should try and update them all to point to the latest versions at some point.

**Pull request merged**
